- src/Serializer.cpp
Fixes some bugs relating to timer saving introduced by  #124 
I forgot a return statement in the writeFunction Lua callback in case of no errors. Also forgot to save whether or not a timer is loopable and its original trigger time for recreating the timer.
> Fix timer saving

- src/Script.cpp
- src/Serializer.cpp
- src/Serializer.h
Open the way to slimmer save files by allowing game developers to specify what they want saved by putting it in a table named `dgPersistence`. Hence this pull request changes Dagon's behaviour from attempting to save the entire global table (introduced in #119) to attempting to save just the aforementioned table.
I've also updated the save file format to a non-destructive one.
@agustincordes I did this in the way I discussed with you over email almost two weeks ago. I was able to do this because I think I have found a way to work around the issue of not knowing if it's safe to add to a table.
For the uninitiated, this change happened by converting what would have been `t={42}` into `dgPersistence["t"][1]=42`. This way, the loading of the save file will add to the table `t` rather than …
> Rework saving of Lua variables

- src/Serializer.cpp
- src/Serializer.h
Update the code that handles cycles to use references instead of string keys into the Lua registry, because it is a more elegant solution and because it is how the rest of Dagon interacts with Lua's registry.
> Make Serializer use Lua refs

- src/dirent.c
Building on a platform other than Windows should have been broken since #119. The reason is the addition of `dirent.c` which surely won't compile anywhere but Windows.
> Fix non-Windows builds

- src/Serializer.cpp
This one is just downright embarrassing... in #127 I basically broke all of serialization by forgetting one line... I forgot that creating a Lua reference pops the value from the stack. Can you imagine how hard I panicked when I thought it was the new deserialization I've been working on all day that caused that?
Please merge ASAP and let me forget about it forever....
> Fix table storing

- src/Deserializer.cpp
- src/Script.cpp
- src/Serializer.cpp
The first part of this is just kinda funny. `SDL_RWwrite` (and friends) will return the number of objects written so if the description string is empty when saving in a Node, it will correctly return zero which is then evaluated as false by C++ which causes it to abandon the save.
Also undoes 12fb99f41dbc591dffddd9881bbbb7481bbf0bdf as it apparently breaks loading. I have absolutely no idea why though, but the changes in that commit cause the engine to crash at https://github.com/bd339/Dagon/blob/master/src/Script.cpp#L727 when switching rooms. It probably has to do with `DGCheckProxy` not doing what I expect it to. It returns 1 (`kObjectGeneric`) for something I am certain ought to be a Room. Please enlighten me someone.
> Fix saving in Node with empty description

- src/Deserializer.cpp
- src/Serializer.cpp
By doing more testing in the Seclusion demo, I discovered that sometimes the field of view changes and loading might then cause black bars to appear around the edge of the viewport.
> Persist field of view

- src/Deserializer.cpp
- src/Serializer.cpp
Add a 9 byte identifier to the beginning of each save file, so we can verify that the file we are trying to load is likely a save file produced by Dagon and not of some unknown origin.
> Add magic number to save files

- src/SlideProxy.h
I thought that adding `onPersist ` and `onUnpersist ` callbacks for Nodes in #134 would also allow those callbacks for Slides because creating a Slide from Lua just creates a Node and marks it as a Slide. Needless to say, I was wrong and my misunderstanding has now been corrected by adding the same callbacks to Slides.
> Add Slide callbacks

- src/Control.cpp
- src/Control.h
- src/Script.cpp
Until now, whenever you load into a Room that already exists in the engine, it would create a new Room and remove the old Room from the list of Rooms. Now it will merge the save file's data with the existing Room and only create a new Room if the Room we are loading into doesn't exist yet.
> Merge Rooms when possible

- src/TimerManager.cpp
- src/TimerManager.h
Before we were returning the vector of timers as a copy, so the Deserializer was rewinding time on a copy of a timer. Fixed (in an ugly way) by returning a reference to the member instead of a copy.
Btw, the timer code is completely untested as Seclusion doesn't use it atm so I expect it to break horrendously first time someone actually needs it...
> Rewind start time on original timer, not copy

- src/Control.cpp
- src/Control.h
- src/Deserializer.cpp
- src/Script.cpp
- src/Script.h
- src/Serializer.cpp
Before this change save files were unjustly flimsy. Even minor script changes that shouldn't affect a save file would invalidate it. Now we should be fine as long as Dagon users don't rename their Lua variables (we hash Lua variable names to identify objects across sessions).
Some of these changes are not directly related to the hashing, but they handle some corner cases to avoid crashing if loading a corrupt save file, or saving at very odd points (outside of any Room or Node for example).
> Make save files more robust

- src/Deserializer.cpp
- src/Deserializer.h
- src/Script.cpp
- src/Serializer.cpp
It has never been a problem to save in a Slide and return the player to that Slide, but because the previous node was never saved it could switch you to an unexpected Node when you exit the Slide. Nothing gamebreaking for Serena for example, but once games allow you to load from a main menu things can get really screwy when you return to the "main menu Node" when exiting the Slide you loaded into, for example.
I've been holding off on this patch because Seclusion uses it own code to switch to and from Slides (this patch shouldn't break that) but this patch seems to provide the correct behaviour for Serena at least.
> Correct behaviour for Slide persistence

- src/Node.cpp
Once in a Blue Moon (okay, slightly more often), Dagon would crash on shutdown from calling a method on an invalid Spot pointer.
Seeing this, imagine how sexy it would be if modern C++ like this was available when the majority of Dagon's code was written.
> Fix occasional™ shutdown crash

- src/Serializer.cpp
Previously the Spots automatically created by Dagon by it's Node linking feature were also looked for in the object map. This filled the log with plenty of red herrings, warning about plenty of Spots that will not have their state saved.
> Only look for user created Spots

- src/Serializer.cpp
- src/Spot.cpp
- src/Spot.h
Currently this warning is our best indication that a user has name duplicates, so it should include the coordinates of the Spot in question to make it easier to determine if and where multiple Spots are assigned to the same variable by searching across their script files (editors like Notepad++ allow this) for those coordinates.
> Include coordinates in unmapped Spot warning

- src/Control.cpp
Tries to resolve the discussion in #147. It does this by only affecting room specific audio when switching rooms and when switching nodes it will add all of the autoplaying audio objects attached to spots of the target node to a set: `targetNodeAudios` and all of the autoplaying audio objects attached to spots of the current node will be added to a set: `curNodeAudios`. To find out which audio objects should stop playing the set difference `curNodeAudios \ targetNodeAudios` will be computed (the resulting set will be the set of all audio objects in `curNodeAudios` but not in `targetNodeAudios`). When deciding what audios should begin playing when we switch to the new node, the set difference `targetNodeAudios \ curNodeAudios` will be computed (the resulting set will be the set of all …
> Change audio behaviour when switching nodes

- src/AudioManager.cpp
- src/AudioManager.h
- src/Control.cpp
- src/Room.cpp
- src/Room.h
This PR changes the mechanism for releasing audio resources. Now audio resources will not be released once the engine determines they are no longer needed, but will release **all** audio resources contained within a room when you switch rooms - except for those resources that will be used in the new room (as agreed upon in #149)
This change probably makes some code unnecessary but I am not sure which atm, so I suggest removing that in follow-ups. We will probably also want to enforce this change of policy for other room resources as well (videos for instance), but likewise I propose that to be done in follow-ups.
> Only release audio resources on room change

- src/CameraManager.cpp
Perhaps not the prettiest way to fix #121 , but I find the camera code to be rather difficult to follow so I went with it anyway.
The `lookAt` command would occasionally turn right even though it would have been shorter to turn left (or vice versa) and it seems to have been caused by `_deltaX = static_cast<int>((_angleHTarget - _angleH) * 360);`
Consider `_angleHTarget = (3/2) * PI` and `_angleH = 0`. In this example `_deltaX` will be positive. That means the camera will turn 270° to the right instead of 90° to the left.
In general this means that when there is more than 180° between the target direction and the current direction, the camera will turn in the "wrong" direction.
> Never turn more than 180 degrees as a result of the lookAt command

- src/Control.cpp
- src/Control.h
- src/Platform.h
- src/Script.cpp
This change allows developers to assign `i`, `j`, `l`, `o`, `p`, as hotkeys through the `KEY_i`, `KEY_j`, `KEY_l`, `KEY_o`, `KEY_p` constants respectively.
One can also override the default behaviour of the escape and space keys by assigning `ESC` and `SPACE` like you would any other hotkeys.
> Add more hotkeys and allow overriding escape & space

- src/Script.cpp
It was brought to my attention that Seclusion was faced with undesired behaviour when loading while a timer was running: The timer kept running after the load.
This was intentionally left at such because I don't quite trust the timer persistence system yet. It remains one of the most untested parts after all, so I opted to let timers run in case a timer that was supposed to have been saved couldn't be brought back.
But now that decision is causing pain I decided to "fix" it. Keep in mind that this means that if you have any timers you find aren't persisted correctly, you might have to use the [persistence system callbacks](https://github.com/Senscape/Dagon/wiki/Persistence#callbacks) to manually bring them back after loading.
> Stop timers started through script when loading a saved game

- src/Interface.cpp
- src/Overlay.cpp
- src/Overlay.h
- src/OverlayProxy.h
This defines default cursor for an Overlay as "the cursor to be displayed when no Buttons are hovered". It's defined this way because currently Buttons are the only elements that change the cursor in an Overlay.
The default cursor can be set from Lua by calling the `setDefaultCursor` function on an Overlay. The only parameter is the cursor to use, and any parameter value that is valid for `setCursor` on Button etc. is also valid for `setDefaultCursor`.
It was requested for Seclusion: Islesbury because the current behaviour means that if you hover a e.g. an inventory item (implemented as a Button which changes the cursor), the cursor will stay the same until another Button is hovered, causing the cursor to "linger" when no Button is hovered.
> Default cursor for Overlays

- src/Control.cpp
`kKeyQuote` conflicted with the `5` key, both numpad and otherwise, on mine and Civan's keyboards. As a result it was impossible to type `5` in the console so I just removed the shortcut. I really don't understand why that conflict exists however. `kKeyQuote` equals `SDL_SCANCODE_GRAVE` (53) if that means anything to anyone?
> Only allow console to be toggled by tab.

- visualc/Dagon.vcxproj
Remove -Wall because it will generate around 20k warnings from the msvc implementation of standard libraries. Bump warning level up to 4 instead of 3. Use multiprocessor compilation when available.
> Optimize config for VS2015 builds.

- src/Control.cpp
- src/Control.h
- src/Room.cpp
- src/Room.h
When a room switch occurs, we will now transfer audio assets that are not immediately ready to be unloaded (i.e. they need to be faded) to the next room. This might delay unloading until the next room switch, but it is a much more robust way of making sure the fading in between rooms work correctly.
> Transfer assets on room change

- src/RoomProxy.h
In #161 I introduced a new way of adding room audio. This makes that API consistent with the rest, in the sense that you will now be able to do e.g. `room:addAudio("a.ogg", { volume = 70, varying = true })`. So it basically just allows optional parameters to be specified by name, in a table. Auto and loop are forced to true.
> Make new room audio API consistent

- src/AudioAsset.h
- src/AudioManager.cpp
- src/Config.cpp
- src/Config.h
In e21d704 I did a rather lazy fix for a bug where the path to an audio asset could be resolved to different paths during runtime, depending on the circumstances the path was generated under. This atones for that by falling back to looking for the asset in the general folder, it if couldn't be found in a room specific folder.
> Improve code for resolving asset paths

- src/Audio.cpp
- src/Audio.h
- src/AudioManager.cpp
- src/AudioProxy.h
- src/Control.cpp
- src/Deserializer.cpp
- src/FeedManager.cpp
- src/Script.cpp
- src/Spot.cpp
All sorts of deadlocks can be imagined from the audio code I merged in #161. At least one would sometimes show itself in Seclusion. At the heart of the problem is how the AudioManager locks both itself and Audio objects, and Audio objects also lock the AudioManager. This allows for the AudioManager to hold a lock on an Audio object in one thread, and for the audio object to hold a lock on the AudioManager in another thread. The fix then, is to disentangle Audio objects from the AudioManager in the sense that Audio objects won't lock the AudioManager, but the AudioManager can still lock the Audio objects it manages.
> Fix deadlocks in audio code

- src/Control.cpp
- src/Control.h
Currently we force the control mode to "fixed" when the player returns from a slide. This change stores the current control mode in a `_prevControlMode` variable when the player goes from a node to a slide. When the player returns from a slide, we restore the control mode. `_prevControlMode` is set to "free" by default, in case the player loads the game into a slide from a savegame. If it turns out to be necessary, we can update the persistence code to include the `_prevControlMode` variable in the save files.
Actually the code that forces the control mode to "fixed" is still in place, this change just overrides that behaviour for slides.
> Don't force control mode when leaving slides

- src/Control.cpp
After changing control mode (depending on from which and to which you switch), the neutral zones need to be updated by a call to `CameraManager::setViewport`. Ideally a function like
```c++
void setControlMode(int mode) {
config.controlMode = mode;
cameraManager.setViewport(config.displayWidth, config.displayHeight);
}
```
Should have been defined to make sure we don't forget this step, but there's not much point when the code is already full of "raw" access to `config.controlMode`.
> Update neutral zones after changing control mode

- src/System.cpp
Another one to add to the pile towards #166 . Gradually this has been tested pretty thoroughly by Cleo on Windows 7, Civan on Windows 8.1, Nige and I on Windows 10 (I have a high dpi monitor). Thanks guys.
> Force a reshape when going to windowed mode

- src/Font.cpp
```../src/Font.cpp: In member function ‘void dagon::Font::_loadFont(FT_FaceRec_*&)’:
../src/Font.cpp:204:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int j = 0; j < height; j++) {
^
../src/Font.cpp:205:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
for (int i = 0; i < width; i++) {
^
../src/Font.cpp:208:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
(i >= bitmap.width || j >= bitmap.rows) ?
^
../src/Font.cpp:208:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
(i >= bitmap.width || j >= bitmap.rows) ?
^```
> Font.cpp: silence g++ sign-compare warning

- src/Script.cpp
```
../src/Script.cpp: In static member function ‘static int dagon::Script::_globalNewIndex(lua_State*)’:
../src/Script.cpp:356:44: warning: left shift count >= width of type [-Wshift-count-overflow]
uint64_t hash = uint64_t(hashBuf[0] << 56) | uint64_t(hashBuf[1] << 48) |
^
../src/Script.cpp:356:73: warning: left shift count >= width of type [-Wshift-count-overflow]
uint64_t hash = uint64_t(hashBuf[0] << 56) | uint64_t(hashBuf[1] << 48) |
^
../src/Script.cpp:357:44: warning: left shift count >= width of type [-Wshift-count-overflow]
uint64_t(hashBuf[2] << 40) | uint64_t(hashBuf[3] << 32) |
^
../src/Script.cpp:357:73: warning: left shift count >= width of type [-Wshift-count-overflow]
uint64_t(hashBuf[2] << 40) | uint64_t(hashBuf[3] << 32) |
^
```
> Script.cpp: silence g++ shift-count-overflow warnings

- src/Image.cpp
- src/Texture.cpp
- src/Texture.h
Some games use Image objects extensively. Examples include inventory items and journal entries. Hence it is quite inefficient to load the texture backing the Image and uploading it to the GPU, as soon as the Image is created. With this change we defer that work until the Image is first shown.
In order to preserve semantics (e.g. being able to query an Image for its size as soon as it's created), the size needs to be available immediately after creation. This is implemented by loading the bitmap and reading its size and then immediately unloading it. Unfortunately this means we load and unload every bitmap twice (obviously not time efficient). I'd be more than happy to implement a suggestion that give us the size of the bitmap without loading the entire thing.
> Defer loading Image textures

- src/Image.cpp
Effectively reverts #173 . The simple method of reading PNG dimensions from the header doesn't always work. It gives the exact dimensions for some images, but some of them can be slighty off (maybe just one direction).
> Go back to letting STBI handle all image loading

- src/CameraManager.cpp
- src/CameraManager.h
- src/Control.cpp
Attempt at fixing #186 . My theory is that some configurations fire more mouse move events hence calling `directPan` more often, each time adding to `_angleH` and `_angleV`. At least that theory is consistent with the observations in [this comment](https://github.com/Senscape/Dagon/issues/186#issuecomment-270028839), so I'm going with it :smile:
The fix is to only call `directPan` when the camera updates, because that happens at a constant rate. Assuming linear growth of `directPan` (looks like it to me from the code) this does not change the general camera speed, because we would be reducing the number of `directPan`  calls by some factor, but increasing the observed mouse movement by the same factor.
Bottom line is, it works on my Linux test machine and didn't change the camera speed …
> Fix fixed mode camera speed

- src/Control.cpp
- src/Control.h
- src/SystemLib.h
One bug fix, but primarily saner defaults (imo).
@civanT noticed that pressing tab (opening console) outside of debug mode render user-defined keybindings like space ineffective. The fix is to simply check for debug mode when pressing tab (only way to open the console that I know of, since we removed F5). I never really looked into why toggling the console outside of debug mode is troublesome to begin with. It clearly does something that is not easily reversed by pressing tab again...
Besides that fix, I have removed the default behavior for space and escape keys. Since they can now be bound like many other keys, you can restore the old behavior with
```lua
hotkey(SPACE, "system.toggleHelpers()")
hotkey(ESC, "system.terminate()")
```
> Hotkey changes

- src/Language.h
- src/Scene.cpp
- src/Scene.h
- src/Spot.cpp
- src/Spot.h
- src/SpotProxy.h
With this change it's now possible to assign a callback for the hover event on Spots, from Lua.
Example use:
````lua
mySpot:onHover(function()
-- do interesting stuff here
self:onHover(function() -- overwrite the hover event when hovered
-- note that "self" refers to the Spot that was hovered
-- useful if assigning the same function to different Spots
print("hover-ception")
end)
end)
````
> on(Un)hover callback for Spots

- src/Scene.cpp
- src/Scene.h
Make sure to trigger onUnhover even if the cursor moves from one spot to
another without leaving a spot (e.g. there's an overlap or you're moving
your mouse wicked fast)
> Hover fixes

- src/Script.cpp
If a node is aliased, the last registered alias would be saved. This is a problem since that alias is rarely available when loading. We should save its first name instead since that name is more likely to be present when loading.
This applies to all objects we support saving, but nodes in particular are subject to aliasing.
> Fix a bug with loading (mostly affected nodes)
